### ISSUE TITLE
Enchantment Descriptions compat

### ISSUE THREAD

**Issue by onemorelevel0** [team-abnormals/allurement#18]
Hello, love these enchantments here. I was just wondering if you guys were looking to add compat for the Enchantment Descriptions mod. I'm not sure if it's something you'd be interested to do but I saw on one of their [own issues](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues/61) that they preferred for individual mods to add the descriptions themselves since apparently a lot of enchantment description mods use the same data format

**Comment by bageldotjpg** [comment]
This is already in the mod and has been for a while
