### ISSUE TITLE
Can't parse horse armour loot table

### ISSUE THREAD

**Issue by Nebula240** [team-abnormals/allurement#26]
I've been getting this issue with the latest version of allurement on my modpack.
Happens server and clientside.

This is on The Cube Reborn 3.1, using Allurement 1.2.0
https://paste.ubuntu.com/p/YNtKq4zQWx/

**Comment by Wedge1453** [comment]
found it in my server's log
![Screenshot_1](https://user-images.githubusercontent.com/76813383/133345279-fcf10cab-fc87-4f9e-985d-303b0827d8d8.png)

**Comment by bageldotjpg** [comment]
Fixed as of latest release
