### ISSUE TITLE
[ SUGGESTION ] Have a balance tweak to make Infinity and Reforming not be mutually exclusive.

### ISSUE THREAD

**Issue by Huantanhua** [team-abnormals/allurement#42]
Although Infinity and Mending are mutually exclusive in the vanilla. However, the working mechanism of Reforming and Mending are different. So, I think that this mod should remove the boundary between Infinity and Reforming, and it may not affect the balance.
Sorry, my English is not very good.

**Comment by bageldotjpg** [comment]
This Is intentional, especially as it can be a lot easier in certain conditions to repair an item with reforming.
