### ISSUE TITLE
Reeling Enchant incompatibility with Upgraded Netherite Crossbows

### ISSUE THREAD

**Issue by Alexander282** [team-abnormals/allurement#45]
Reeling stops working when applied to any crossbow from the Upgraded Netherite mod.

**Comment by Alexander282** [comment]
Update: None of the Allurement enchants work with Upgraded Netherite items.

**Comment by bageldotjpg** [comment]
Unfortunately that mod does not have their source posted on github, so there is not much I can do to look into it. I believe this would certainly be an issue with their mod though, as our enchantments work fine on plenty of modded weapons and armors.
