### ISSUE TITLE
Crash on Startup.

### ISSUE THREAD

**Issue by xelotex** [team-abnormals/allurement#56]
I don't have any idea why, yesterday it loaded fine, but now it just crashes. Thought it was incompatible with some mod that i installed, but no. I tried to run the mod alone and it still won't load. I'm using the same mod loader, same everything as yesterday, but it just won't load today.

Just allurement installed:
![Captura de pantalla (165)](https://github.com/team-abnormals/allurement/assets/70168682/e3c15380-9de3-4402-9567-14265c1def73)

It didn't generate any crash reports so i'll leave the log files:
[debug.log](https://github.com/team-abnormals/allurement/files/15285425/debug.log)
[latest.log](https://github.com/team-abnormals/allurement/files/15285426/latest.log)

**Comment by bageldotjpg** [comment]
You need Blueprint

**Comment by xelotex** [comment]
Oh, thank you. But mark blueprint as a requirement pls.

![Captura de pantalla (166)](https://github.com/team-abnormals/allurement/assets/70168682/f2434fb0-a23b-4eeb-a38b-28ad9f85809c)
