### ISSUE TITLE
Mixin Crash when not using Quark

### ISSUE THREAD

**Issue by Caltinor** [team-abnormals/allurement#7]
Allurement Version: 1.16.5-1.1.0

Crashes due to an NPE related to being unable to find Quark

[2021-03-24-2.log.gz](https://github.com/team-abnormals/allurement/files/6199190/2021-03-24-2.log.gz)

**Comment by bageldotjpg** [comment]
Fixed in latest release

**Comment by Caltinor** [comment]
Awesome Thank you!
