### ISSUE TITLE
Config file creates a new backup of itself every time the game is started up

### ISSUE THREAD

**Issue by Not-February** [team-abnormals/allurement#9]
This happens even if the config file wasn't altered, and if it *was* altered, the values are kept in the current .toml file, so it technically is working... it's just the config folder ends up filling with new 'allurement-common-#.toml.bak' files every single time you boot up the game, adding a new one even if you left the old one(s) there.

Just tested this with only `abnormals_core-1.16.5-3.1.1`, `allurement-1.16.5-1.1.1`, and `Forge 36.1.4` installed on 1.16.5. I ended up with both `allurement-common.toml` and a `allurement-common-1.toml.bak` file on the first run of the game.

**Comment by ChloeDawn** [comment]
It appears to be an issue with floating-point imprecision during parsing
```
Configuration file E:\Minecraft\CurseForge\Instances\...\config\allurement-common.toml is not correct. Correcting
Incorrect key enchantments.alleviating.Healing factor was corrected from 0.25 to its default, 0.25. 
Incorrect key enchantments.vengeance.Damage factor was corrected from 0.025 to its default, 0.025. 
Incorrect key tweaks.soul_speed.Damage factor was corrected from 1.5 to its default, 1.5. 
Configuration file E:\Minecraft\CurseForge\Instances\...\config\allurement-common.toml is not correct. Correcting
```
